openapi: 3.0.0
info:
  version: 1.0.0
  title: 京东
servers:
  - url: 'https://bizapi.jd.com/api/'
paths:
    /product/getCategory:
        post:
            summary: '获取类目信息'
            tags: 
              - product
            parameters:
                - name: token
                  in: query
                  description: '固定值'
                  schema:
                      type: string
                  required: true
                - name: cid
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int32
            responses:
                '200':
                    description: '类目信息'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CategoryResponse'
                default:
                    description: 异常报错
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /product/getDetail:
        post:
            summary: '获取商品详情'
            tags: 
              - product
            description: "获取商品详情"
            parameters:
              - name: sku
                in: query
                description: "sku id"
                schema:
                    type: string
                required: true
              - name: token
                in: query
                schema:
                    type: string
              - name: queryExts
                in: query
                schema:
                    type: string
            responses:
                "200":
                    description: '商品详情响应'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SkuDetailResponse'
    /product/getPageNum:
        post:
            summary: '获取商品池'
            tags: 
              - product
            description: "获取商品池"
            parameters:
              - name: token
                in: query
                schema:
                    type: string
                required: true
            responses:
                "200":
                    description: '商品池响应'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProductPoolResponse'
    /product/getSkuByPage:
        post:
            summary: '获取商品池内skuid'
            tags: 
              - product
            description: "获取商品池内商品列表"
            parameters:
              - name: token
                in: query
                schema:
                    type: string
                required: true
              - name: pageNum
                in: query
                schema:
                    type: string
                required: true
              - name: pageNo
                in: query
                schema:
                    type: integer
                required: true
            responses:
                "200":
                    description: '商品池商品页面响应'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PoolPageResponse'
    /product/getSimilarSku:
        post:
            summary: '获取同类商品'
            tags:
              - product
            parameters:
              - name: sku
                in: query
                description: "sku id"
                schema:
                  type: string
                required: true
              - name: token
                in: query
                schema:
                    type: string
            responses:
                "200":
                    description: '获取同类商品'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SimilarSkuResponse'
    /product/totalCheckNew:
        post:
            summary: '商品可购状态'
            tags:
                - product
            parameters:
                - name: token
                  in: query
                  schema:
                      type: string
                - name: skuIds
                  in: query
                  schema:
                      type: string
                      example: '1,2'
                - name: province
                  in: query
                  schema:
                      type: string
                      description: '省，京东一级地址编号'
                - name: city
                  in: query
                  schema:
                      type: string
                      description: '市，京东二级地址编号'
                - name: county
                  in: query
                  schema:
                      type: string
                      description: '县，京东三级地址编号'
                - name: town
                  in: query
                  schema:
                      type: string
                      description: '镇，京东四级地址编号'
            responses:
                "200":
                    description: "商品可购状态返回"
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TotalCheckResponse'

    /price/getSellPrice:
        post:
            summary: '获取商品价格'
            tags:
              - price
            parameters:
              - name: sku
                in: query
                description: "商品编号，请以，(英文逗号)分割"
                example: '129408,129409'
                schema:
                  type: string
                required: true
              - name: skuInfos
                in: query
                schema:
                    type: array
                    items:
                        type: "object"
                        properties:
                            skuId:
                                type: integer
                            num:
                                type: integer
                                default: 1
              - name: token
                in: query
                schema:
                    type: string
            responses:
                "200":
                    description: '获取商品详情'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SkuPriceResponse'
     
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    CategoryResponse:
      type: "object"
      properties:
        result:
          $ref: "#/components/schemas/Category"
        resultCode:
          type: integer
          format: int32
        resultMessage:
          type: string
        success:
          type: boolean
          default: true
    PoolPageResponse:
       properties:
        result:
          $ref: "#/components/schemas/ProductPoolPage"
        resultCode:
          type: integer
          format: int32
        resultMessage:
          type: string
        success:
          type: boolean
          default: true 
    SkuDetailResponse:
       properties:
        result:
          $ref: "#/components/schemas/SkuDetail"
        resultCode:
          type: integer
          format: int32
        resultMessage:
          type: string
        success:
          type: boolean
          default: true
    SimilarSkuResponse:
        properties:
            result:
                type: array
                items:
                    $ref: "#/components/schemas/SimilarSku"
            resultCode:
                type: integer
                format: int32
            resultMessage:
                type: string
            success:
                type: boolean
                default: true
    SkuPriceResponse:
        properties:
            result:
                type: array
                items:
                    $ref: "#/components/schemas/SkuPrice"
            resultCode:
                type: integer
                format: int32
            resultMessage:
                type: string
            success:
                type: boolean
                default: true
    totalCheckResponse:
        properties:
            result:
                type: array
                items:
                    $ref: "#/components/schemas/SkucanPurchaseMsg"
            resultCode:
                type: integer
                format: int32
            resultMessage:
                type: string
            success:
                type: boolean
                default: true
    SkucanPurchaseMsg:
        properties:
            skuId:
                type: integer
                minimum: 0
            canPurchase:
                type: boolean
            message:
                type: string    
    SkuPrice:
        properties:
            price:
                type: number
                format: double
            skuId:
                type: integer
            jdPrice:
                type: number
                format: double
            tax:
                type: number
                format: double
            taxPrice:
                type: number
                format: double
            nakedPrice:
                type: number
                format: double
    SkuDetail:
        type: "object"
        properties:
            saleUnit:
                type: string
            weight:
                type: string
            wserve:
                type: string
            productArea:
                type: string
            wareQD:
                type: string
            imagePath:
                type: string
            param:
                type: string
            state:
                type: integer
                format: int1
            sku:
                type: integer
                format: int64
            brandName:
                type: string
            upc:
                type: string
            category:
                type: string
            name:
                type: string 
            introduction:
                type: string
    Category:
        type: "object"
        required:
          - catId
        properties:
            catClass:
                type: integer
            catId:
                type: integer
            name:
                type: string
            parentId:
                type: integer
            state:
                type: integer
    ProductPoolResponse:
        type: "object"
        properties:
            result:
                type: array
                items:
                    type: "object"
                    properties:
                        name:
                            type: string
                        page_num:
                            type: string
            resultCode:
                type: integer
                format: int32
            resultMessage:
                type: string
            success:
                type: boolean
                default: true
    ProductPoolPage:
        type: "object"
        properties:
            pageCount:
                type: integer
            skuIds:
                type: array
                items:
                    type: integer
    SimilarSku:
        type: "object"
        properties:
            dim:
                type: integer
            saleName:
                type: string
            saleAttrList:
                type: array
                items:
                    $ref: "#/components/schemas/SaleAttr"
    SaleAttr:
        type: "object"
        properties:
            imagePath:
                type: string
            saleValue:
                type: string
            skuIds:
                type: array
                items: 
                    type: integer
  securitySchemes:
    oauth2:
      type: "oauth2"
      flows:
        implicit:
          authorizationUrl: "https://bizapi.jd.com/oauth2/accessToken"
          scopes:
            read: "example read scope"
            write: "example write scope"
security:
  - oauth2: []