openapi: 3.0.0
info:
  version: 1.0.0
  title: 京东
servers:
  - url: 'https://bizapi.jd.com/api/'
paths:
    /product/getCategory:
        post:
            summary: '获取类目信息'
            tags: 
              - product
            parameters:
                - name: token
                  in: query
                  description: '固定值'
                  schema:
                      type: string
                  required: true
                - name: cid
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int32
            responses:
                '200':
                    description: '类目信息'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CategoryResponse'
                default:
                    description: 异常报错
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /product/getDetail:
        post:
            summary: '获取商品详情'
            tags: 
              - product
            description: "获取商品详情"
            parameters:
              - name: sku
                in: query
                description: "sku id"
                schema:
                    type: string
                required: true
              - name: token
                in: query
                schema:
                    type: string
              - name: queryExts
                in: query
                schema:
                    type: string
            responses:
                "200":
                    description: '商品详情响应'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SkuDetailResponse'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    CategoryResponse:
      type: "object"
      properties:
        result:
          $ref: "#/components/schemas/Category"
        resultCode:
          type: integer
          format: int32
        resultMessage:
          type: string
        success:
          type: boolean
          default: true
    SkuDetailResponse:
       properties:
        result:
          $ref: "#/components/schemas/SkuDetail"
        resultCode:
          type: integer
          format: int32
        resultMessage:
          type: string
        success:
          type: boolean
          default: true 
    SkuDetail:
        type: "object"
        properties:
            saleUnit:
                type: string
            weight:
                type: string
            wserve:
                type: string
            productArea:
                type: string
            wareQD:
                type: string
            imagePath:
                type: string
            param:
                type: string
            state:
                type: integer
                format: int1
            sku:
                type: integer
                format: int64
            brandName:
                type: string
            upc:
                type: string
            category:
                type: string
            name:
                type: string 
            introduction:
                type: string
    Category:
      type: "object"
      required:
          - catId
      properties:
        catClass:
          type: integer
        catId:
          type: integer
        name:
          type: string
        parentId:
          type: integer
        state:
          type: integer
  securitySchemes:
    oauth2:
      type: "oauth2"
      flows:
        implicit:
          authorizationUrl: "https://bizapi.jd.com/oauth2/accessToken"
          scopes:
            read: "example read scope"
            write: "example write scope"
security:
  - oauth2: []